name: CI/CD Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Secrets
        run: |
          sed -i "s/REPLACE_WITH_PUBLIC_KEY/${{ secrets.EMAILJS_PUBLIC_KEY }}/g" index.html
          sed -i "s/REPLACE_WITH_SERVICE_ID/${{ secrets.EMAILJS_SERVICE_ID }}/g" emailjs.js
          sed -i "s/REPLACE_WITH_TEMPLATE_ID/${{ secrets.EMAILJS_TEMPLATE_ID }}/g" emailjs.js

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages